name: nexo_bank
description: Nexo Bank - app de banca digital para personas (arquitectura hexagonal por feature).
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  # Estado
  flutter_bloc: ^9.1.1
  bloc: ^9.2.1
  equatable: ^3.0.0
  # Red
  dio: ^5.11.1
  connectivity_plus: ^7.3.2
  # Navegación e inyección de dependencias
  go_router: ^18.0.2
  get_it: ^9.3.0
  # Seguridad y almacenamiento (tokens en Keychain/Keystore, caché cifrada)
  flutter_secure_storage: ^11.2.0
  hive_ce: ^2.20.1
  hive_ce_flutter: ^2.4.0
  # Utilidades
  uuid: ^4.6.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true
